// Generated by gencpp from file set_state/SrvIntResponse.msg
// DO NOT EDIT!


#ifndef SET_STATE_MESSAGE_SRVINTRESPONSE_H
#define SET_STATE_MESSAGE_SRVINTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace set_state
{
template <class ContainerAllocator>
struct SrvIntResponse_
{
  typedef SrvIntResponse_<ContainerAllocator> Type;

  SrvIntResponse_()
    : response_int(0)  {
    }
  SrvIntResponse_(const ContainerAllocator& _alloc)
    : response_int(0)  {
  (void)_alloc;
    }



   typedef int32_t _response_int_type;
  _response_int_type response_int;





  typedef boost::shared_ptr< ::set_state::SrvIntResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::set_state::SrvIntResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SrvIntResponse_

typedef ::set_state::SrvIntResponse_<std::allocator<void> > SrvIntResponse;

typedef boost::shared_ptr< ::set_state::SrvIntResponse > SrvIntResponsePtr;
typedef boost::shared_ptr< ::set_state::SrvIntResponse const> SrvIntResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::set_state::SrvIntResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::set_state::SrvIntResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::set_state::SrvIntResponse_<ContainerAllocator1> & lhs, const ::set_state::SrvIntResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response_int == rhs.response_int;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::set_state::SrvIntResponse_<ContainerAllocator1> & lhs, const ::set_state::SrvIntResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace set_state

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::set_state::SrvIntResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::set_state::SrvIntResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::set_state::SrvIntResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::set_state::SrvIntResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::set_state::SrvIntResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::set_state::SrvIntResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::set_state::SrvIntResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eaa684da2e3648981ee22ce4b464424e";
  }

  static const char* value(const ::set_state::SrvIntResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeaa684da2e364898ULL;
  static const uint64_t static_value2 = 0x1ee22ce4b464424eULL;
};

template<class ContainerAllocator>
struct DataType< ::set_state::SrvIntResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "set_state/SrvIntResponse";
  }

  static const char* value(const ::set_state::SrvIntResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::set_state::SrvIntResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 response_int\n"
"\n"
;
  }

  static const char* value(const ::set_state::SrvIntResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::set_state::SrvIntResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response_int);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SrvIntResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::set_state::SrvIntResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::set_state::SrvIntResponse_<ContainerAllocator>& v)
  {
    s << indent << "response_int: ";
    Printer<int32_t>::stream(s, indent + "  ", v.response_int);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SET_STATE_MESSAGE_SRVINTRESPONSE_H
