// Generated by gencpp from file set_state/SrvIntRequest.msg
// DO NOT EDIT!


#ifndef SET_STATE_MESSAGE_SRVINTREQUEST_H
#define SET_STATE_MESSAGE_SRVINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace set_state
{
template <class ContainerAllocator>
struct SrvIntRequest_
{
  typedef SrvIntRequest_<ContainerAllocator> Type;

  SrvIntRequest_()
    : request_int(0)  {
    }
  SrvIntRequest_(const ContainerAllocator& _alloc)
    : request_int(0)  {
  (void)_alloc;
    }



   typedef int32_t _request_int_type;
  _request_int_type request_int;





  typedef boost::shared_ptr< ::set_state::SrvIntRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::set_state::SrvIntRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SrvIntRequest_

typedef ::set_state::SrvIntRequest_<std::allocator<void> > SrvIntRequest;

typedef boost::shared_ptr< ::set_state::SrvIntRequest > SrvIntRequestPtr;
typedef boost::shared_ptr< ::set_state::SrvIntRequest const> SrvIntRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::set_state::SrvIntRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::set_state::SrvIntRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::set_state::SrvIntRequest_<ContainerAllocator1> & lhs, const ::set_state::SrvIntRequest_<ContainerAllocator2> & rhs)
{
  return lhs.request_int == rhs.request_int;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::set_state::SrvIntRequest_<ContainerAllocator1> & lhs, const ::set_state::SrvIntRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace set_state

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::set_state::SrvIntRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::set_state::SrvIntRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::set_state::SrvIntRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::set_state::SrvIntRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::set_state::SrvIntRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::set_state::SrvIntRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::set_state::SrvIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3178d1d7ec6cecacf3be2661f2752839";
  }

  static const char* value(const ::set_state::SrvIntRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3178d1d7ec6cecacULL;
  static const uint64_t static_value2 = 0xf3be2661f2752839ULL;
};

template<class ContainerAllocator>
struct DataType< ::set_state::SrvIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "set_state/SrvIntRequest";
  }

  static const char* value(const ::set_state::SrvIntRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::set_state::SrvIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 request_int\n"
;
  }

  static const char* value(const ::set_state::SrvIntRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::set_state::SrvIntRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request_int);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SrvIntRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::set_state::SrvIntRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::set_state::SrvIntRequest_<ContainerAllocator>& v)
  {
    s << indent << "request_int: ";
    Printer<int32_t>::stream(s, indent + "  ", v.request_int);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SET_STATE_MESSAGE_SRVINTREQUEST_H
