// Generated by gencpp from file set_state/SrvInt.msg
// DO NOT EDIT!


#ifndef SET_STATE_MESSAGE_SRVINT_H
#define SET_STATE_MESSAGE_SRVINT_H

#include <ros/service_traits.h>


#include <set_state/SrvIntRequest.h>
#include <set_state/SrvIntResponse.h>


namespace set_state
{

struct SrvInt
{

typedef SrvIntRequest Request;
typedef SrvIntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SrvInt
} // namespace set_state


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::set_state::SrvInt > {
  static const char* value()
  {
    return "b0ea3c0a4031127490817459e301f614";
  }

  static const char* value(const ::set_state::SrvInt&) { return value(); }
};

template<>
struct DataType< ::set_state::SrvInt > {
  static const char* value()
  {
    return "set_state/SrvInt";
  }

  static const char* value(const ::set_state::SrvInt&) { return value(); }
};


// service_traits::MD5Sum< ::set_state::SrvIntRequest> should match
// service_traits::MD5Sum< ::set_state::SrvInt >
template<>
struct MD5Sum< ::set_state::SrvIntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::set_state::SrvInt >::value();
  }
  static const char* value(const ::set_state::SrvIntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::set_state::SrvIntRequest> should match
// service_traits::DataType< ::set_state::SrvInt >
template<>
struct DataType< ::set_state::SrvIntRequest>
{
  static const char* value()
  {
    return DataType< ::set_state::SrvInt >::value();
  }
  static const char* value(const ::set_state::SrvIntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::set_state::SrvIntResponse> should match
// service_traits::MD5Sum< ::set_state::SrvInt >
template<>
struct MD5Sum< ::set_state::SrvIntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::set_state::SrvInt >::value();
  }
  static const char* value(const ::set_state::SrvIntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::set_state::SrvIntResponse> should match
// service_traits::DataType< ::set_state::SrvInt >
template<>
struct DataType< ::set_state::SrvIntResponse>
{
  static const char* value()
  {
    return DataType< ::set_state::SrvInt >::value();
  }
  static const char* value(const ::set_state::SrvIntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SET_STATE_MESSAGE_SRVINT_H
