global_costmap:
  publish_voxel_map: true
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 10.0
  transform_tolerance: 0.5
  robot_radius: 0.6
  static_map: true
  obstacle_range: 3.0
  raytrace_range: 3.5
  footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
  map_type: costmap



  plugins:
    - {name: static, type: "costmap_2d::StaticLayer"}
    - {name: inflation, type: "costmap_2d::InflationLayer"}
    - {name: obstacles, type: "costmap_2d::VoxelLayer"}

  static:
    map_topic: map

  inflation:
    inflation_radius: 1.1
    cost_scaling_factor: 3.0

  obstacles:
    observation_sources: scan
    scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}
